import { useTheme } from "next-themes";
import Head from "next/head";
import Browser from "./components/Browser";
import { MoonIcon, SunIcon } from "@heroicons/react/24/outline";

export default function Home() {
  const { theme, setTheme } = useTheme("dark");

  console.log("haha", theme);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="p-3">
        <Browser theme={theme} setTheme={setTheme} />
      </main>

      <footer></footer>
    </div>
  );
}
