import Head from "next/head";
import Browser from "./components/Browser";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="p-3">
        <Browser />
      </main>

      <footer></footer>
    </div>
  );
}
