import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="p-3">
        <div className="bg-gray-300 border border-gray-300 rounded-t-lg flex items-stretch">
          <div className="px-4 pt-4 pb-3 mr-4 text-sm flex-0 text-gray-400 whitespace-nowrap">
            <i className="mx-1 rounded-full w-3 h-3 bg-red-500 inline-block"></i>
            <i className="mx-1 rounded-full w-3 h-3 bg-yellow-500 inline-block"></i>
            <i className="mx-1 rounded-full w-3 h-3 bg-green-600 inline-block"></i>
          </div>
          <div className="flex gap-1">
            <div className="relative px-4 py-2 mt-2 -mb-px flex-0 bg-gray-100 rounded-t-lg">
              <div className="text-sm overflow-hidden pt-1 w-56 whitespace-nowrap">
                Tab heading goes here
              </div>
            </div>
            <div className="relative px-4 py-2 mt-2 -mb-px flex-0 bg-gray-100 rounded-t-lg">
              <div className="text-sm overflow-hidden pt-1 whitespace-nowrap">
                +
              </div>
            </div>
          </div>
        </div>
      </main>

      <footer></footer>
    </div>
  );
}
